version: '3.3'
services:
  app:
    build: .
    ports:
      - 9092:8080
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_HOST: mongo
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: bd_evaluation

  mongo:
    image: mongo
    container_name: mongodbe
    restart: always

    ports:
      - 27022:27017


volumes:
  mongo-data: